os: linux
dist: focal
language: minimal
branches:
    only:
        - master
        - staging
        - trying

addons:
  apt:
    packages:
      - gcc-riscv64-linux-gnu
      - qemu-system-misc
install:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
  - source $HOME/.cargo/env
  - rustup component add rust-src
script:
  - cargo fmt --manifest-path=kernel-rs/Cargo.toml -- --check -l
  - cargo clippy --manifest-path=kernel-rs/Cargo.toml
  - make qemu USERTEST=yes RUST_MODE=release
